### ISSUE TITLE
Incorrect multiplication if multiplier.len == 2

### ISSUE THREAD

**Issue by andrei-ilyin-mh** [bwakell/Huldra#1]
Test script to reproduce:
BigInt a = new BigInt("1000000000000000");
BigInt b = new BigInt("1000000000000000");
a.mul(b);

Result is 2764541310000000000000000 instead of 1000000000000000000000000000000.

Could be fixed by casting operand to long at line 1157:
else if(mul.len==2) umul( **(long)** mul.dig[1]<<32|(mul.dig[0]&mask));

**Comment by bwakell** [comment]
Thanks for spotting the issue.
I don't know how many times I've done that very mistake.

(Now I just have to remember how to update/fix this code that I thought no one, me included, was looking at. ^^)

**Comment by bwakell** [comment]
I'd assume it's fixed now.
If you spot anymore cases like this, please do tell.
