### ISSUE TITLE
BasicTest compile failure

### ISSUE THREAD

**Issue by aaime** [bwakell/Huldra#10]
The testMod method does not compile as BigInt lacks a "mod" method. Replacing the call to "mod" with "rem" or "divRem" results in test failures.

**Comment by aaime** [comment]
A naive implementation mimicking the BigInteger code seems to do the trick:

```
	/**
	 * Mod implementation
	 */
	public void mod(BigInt div) {
		if (div.sign <= 0)
			throw new ArithmeticException("BigInt: modulus not positive");

		this.rem(div);
		if (this.sign < 0) {
			this.add(div);
		}
	}
```

**Comment by bwakell** [comment]
You're completely right. I guess I must have had some local change that includes the mod() operation, but then forgot about it and after that accidentally pushed the test file.

Alternatively, you could just remove the testMod() method.

**Comment by aaime** [comment]
Pushed a simple fix here: https://github.com/bwakell/Huldra/pull/11
