### ISSUE TITLE
Crash during realloc

### ISSUE THREAD

**Issue by exuvo** [bwakell/Huldra#12]
In uassign at line 374
len = 2;
if(dig.length<2) realloc(2);

The realloc crashes if you had created the BigInt with an int (len = 1) and then assign a long as the new len is used inside realloc for System.arraycopy while dig is still of length 1.

The fix is to move down "len = 2" to after the realloc:
if(dig.length<2) realloc(2);
len = 2;

**Comment by bwakell** [comment]
Nice catch! (The test coverage is indeed not ideal. ^^)

Fix committed in https://github.com/bwakell/Huldra/commit/43cc4d94141d09c62fb32a92c9370799fbda7004
