### ISSUE TITLE
uaddMag() error when increasing "len" from 1 to 2

### ISSUE THREAD

**Issue by lebecki** [bwakell/Huldra#14]
Happens when you increase the (positive) BigInt number via adding a positive long.
While adding and "len" should cross the barrier 1->2 this actually does not happen.
Instead "len" remains one. 
This [fix](https://github.com/lebecki/Huldra/commit/b2e166f744d19a76ad292b642e292de94d8e34ce) tries to solve it.

**Comment by bwakell** [comment]
Thanks for reporting and discovering the issue. Pulled and merged your change.
