### ISSUE TITLE
Add bit operations to BigInt class

### ISSUE THREAD

**Issue by jpvee** [bwakell/Huldra#5]
It would be very useful to have the bit-oriented operations (that `java.math.BigInteger` has) in the `BigInt` class as well (things like `and()`, `or()`, `xor()`, `not()`, `andNot()`, `setBit()`, `clearBit()`, `flipBit()`, `testBit()`, `shiftLeft()`, `shiftRight()`) - could these be added?

**Comment by bwakell** [comment]
Sure, should be straightforward enough to add.

**Comment by bwakell** [comment]
So I've added the bit shifts and the test/set/clear/flip bit methods. And for positive numbers they work as expected.
However, for negative numbers we enter an interesting territory. BigInteger imagines the number in two-complement form with infinite sign extension, meaning that e.g. testBit(i) for an i outside the bit-length of the number would return true. The flipBit method would also have a quite interesting behavior... So how do you want it to work for negative numbers? :)

**Comment by jpvee** [comment]
Hmm, I think that adhering to two-complement behavior would correspond to the Principle of Least Surprise, but of course YMMV here.

**Comment by bwakell** [comment]
Yeah after some thinking I think so too.
It's also the way that offers more new/useful functionality. If you want a "normal" bitset, well just use BitSet then instead. ^^

**Comment by bwakell** [comment]
OK I've now adopted test/set/clear/flip bit to be compatible with negative numbers and also implemented bitwise and.
Implementing bitwise operations for negative numbers is however anything but straightforward, and requires immense concentration if you want to do it the efficient way (which we do), but do have a look at the code if you want to see bit-twiddling from hell. :D

**Comment by bwakell** [comment]
Added bitwise xor (and or some weeks ago).
Sorry I didn't make any update last week (and the week before that?), but the new Phoenix Wright game was out so... ^^

**Comment by bwakell** [comment]
Bitwise andNot() and not() added. I believe this issue is resolved then.
