### ISSUE TITLE
Incorrect adding of negative integer

### ISSUE THREAD

**Issue by koldat** [bwakell/Huldra#6]
I am getting ArrayIndexOutOfBoundsException using this very simple test.

Test:
```java
	BigInt acc = new BigInt();
	acc.add(-1L);
        
	Assert.assertEquals("-1", acc.toString());
```
Error:
		java.lang.ArrayIndexOutOfBoundsException: 1

Fix (?):
```java
     public void usub(final long a) //Fix parameter name
     {
         if(sign>0)
         {
             final long ah = a>>>32, al = a&mask;
-            if(len>2 || (dig[1]&mask)>ah || (dig[1]&mask)==ah&&(dig[0]&mask)>=al)
+            if(len>2 || (len == 2 && ((dig[1]&mask)>ah || (dig[1]&mask)==ah&&(dig[0]&mask)>=al)))
             {
                 usubMag(a); return;
             }
```

**Comment by bwakell** [comment]
Well spotted!
I think the if-check would need to be:
`if(len>2 || len==2&&((dig[1]&mask)>ah || (dig[1]&mask)==ah&&(dig[0]&mask)>=al) || ah==0&&(dig[0]&mask)>=al)`
Will try to get it uploaded along with some tests later this week.

The previous code wasn't only prematurely indexing dig[1] (which may not exist) but it was also assuming something about the array-entries outside the number (which you're not allowed to do).

**Comment by koldat** [comment]
Thanks a lot! That would be great.

**Comment by bwakell** [comment]
Should've been fixed now.
