### ISSUE TITLE
benchmarks

### ISSUE THREAD

**Issue by footloosejava** [bwakell/Huldra#7]
You can't benchmark like that. Just changing the order will also change the results.
If you want to benchmark properly, use a profiler, or create a randomizer that changes the order randomly thousands of times, and also changes the jobs to be done randomly, thousands of times.
For example of a proper jvm optimization agnostic test, see:
http://stackoverflow.com/questions/8894258/fastest-way-to-iterate-over-all-the-chars-in-a-string/11876086#11876086

**Comment by alexandergunnarson** [comment]
Agreed, at least for this library / use case. Also, there's something Clojure coders often used called [Criterium](https://github.com/hugoduncan/criterium), which basically warms up the JIT compiler with respect to a particular piece of code and displays statistical results like so:

```
                   Execution time mean : 1.000803 sec
          Execution time std-deviation : 328.501853 us
         Execution time lower quantile : 1.000068 sec ( 2.5%)
         Execution time upper quantile : 1.001186 sec (97.5%)

**Comment by footloosejava** [comment]
It is impressive. There are caveats though. 
For example, let us say I want to create optimized versions of time-consuming crypto algoythms such as this: https://github.com/ethereum/ethereumj/blob/develop/ethereumj-core/src/main/java/org/ethereum/crypto/ECKey.java

Look at "public static byte[] recoverPubBytesFromSignature(int recId, ECDSASignature sig, byte[] messageHash)" around line 1046.

Now ... the challenge is to convert that to using mutable BigInt and then also see if the call to "ECAlgorithms.sumOfTwoMultiplies(CURVE.getG(), eInvrInv, R, srInv)" can also be optimized to using a mutable BigInt.

There is a lot of leftshift/rightshift/add/subtract etc in the entire crypto space there in that codebase.
It takes a lot of time to calculate and creates a lot of new BigIntegers in the process.

But can it be converted? And will it be faster with BigInt used in places?

**Comment by alexandergunnarson** [comment]
@footloosejava I'm confident that any place there's an immutable `BigInteger` used, `BigInt` or  `MutableBigInteger` (p.s. — wondering how that compares to `BigInt`) can be used, as long as the reference to the mutable object isn't passed outside of public-facing functions, which would be thread-unsafe. Not sure on the performance in the general case, but if you don't need to have references to the resulting big integers, then mutable big integers will always be faster than the immutable versions; it's just a question of how much faster. Immutable ones are just easier to reason about, so yes, I'm sure you might introduce bugs if you don't do sufficient regression testing.

**Comment by bwakell** [comment]
Sure if one needs a solid benchmark, then that's the way to go.
But if you only need a rough idea, then the current (ugly) ones are pretty much fine I'd say. Though I did make sure to run each test at least twice to accommodate for the compilation that happens on the first execution, which as seen made quite the difference for some of the other libraries. However, I also think it's of interest to include "first time times" (although flaky) since that's what you're interested in for some applications (e.g. if you wanna make the highscore list on an online judge :P).

Also I'm pretty sure BigInt beats MutableInteger. It might have gotten better with Java 8, but last time I looked at the code there was a lot of suboptimal stuff going on...

That said, I'll let this "issue/bug" be a "implement solid benchmarking". :)

**Comment by footloosejava** [comment]
I was a bit critical. Sorry. The tests do show that it is quite a bit faster!

**Comment by bwakell** [comment]
Nah you were completely right, the current "benchmarks" are anything but beautiful.
(But it's difficult to find motivation to create something better when there are more pressing interesting features to implement.)

Regarding the crypto code, I'm sure it can be optimized, but the question is if it's worth the extra sources of bugs. And the gain all comes down to the usage pattern and the size of the numbers involved. If the operands are small, the operations simple, and the code is frequently executed, then I guess all array creation etc. would be dominant and the impact of a mutable BigInt would be larger.
